### PR TITLE
Adapt for csf function

### PR DESCRIPTION
**Pull request by mmagnuski**
@domstoppable This is 🏗 work in progress (the example does not give errors, but does not work well). But I should make it work pretty soon.

### CODE REVIEW

**Comment by domstoppable** [comment]
@mmagnuski - Looking good so far! Thanks for keeping me posted. Let me know what I can do to help :)

**Comment by mmagnuski** [comment]
@domstoppable I should have some time tomorrow, to get back to this. In the meantime you could think about a reasonable practical test case for this PR (we can talk about criteria for automatic tests too).

**Comment by domstoppable** [comment]
Do you think the CSF measure/estimation is a practical test case?

**Comment by mmagnuski** [comment]
Yes, if you have some data for that, sure.
I'll try to aim for automatic tests (where we simulate a specific function, fit with qp and compare) but am not sure what error margin should we allow - I'll have to figure by trial and error probably or take a look at the paper.

**Comment by mmagnuski** [comment]
Hi @domstoppable, sorry for no updates here. If you are still interested in using quest plus in your experiment I would suggest using Richard's `questplus` package (https://github.com/hoechenberger/questplus) - quest plus is also available in psychopy - `psychopy.data.QuestPlusHandler` (but psychopy uses the questplus package).

**Pull request closed without merging**
